name: untitled1
description: A new Flutter project.

publish_to: 'none'

environment:
  sdk: '>=2.18.6 <3.0.0'

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.5
  flutter_bloc: ^8.1.3
  dio: ^5.2.0
  http: 0.13.5
  pretty_dio_logger: ^1.3.1
  simple_animations: ^4.0.2
  flutter_staggered_animations: ^1.1.1
  pull_to_refresh: ^2.0.0
  flutter_easyloading: ^3.0.5
  readmore: ^2.2.0
  cached_network_image: ^3.2.3
  flutter_rating_bar: ^4.0.1
  provider: ^6.0.5
  flutter_svg: ^1.1.6
  intl: ^0.17.0
  blocer: ^0.0.3

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/
    - assets/images/
  fonts:
    - family: Open Sans
      fonts:
        - asset: assets/fonts/OpenSansLightItalic.ttf
        - asset: assets/fonts/OpenSansRegular.ttf
        - asset: assets/fonts/OpenSansBold.ttf
        - asset: assets/fonts/OpenSansRomanSemiBold.ttf

#
#  fonts:
#    - family: OpenSans
#      fonts:
#        - asset: assets/fonts/OpenSans-Bold.ttf
#        - asset: assets/fonts/OpenSans-Regular.ttf
#        - asset: assets/fonts/SFPRODISPLAYBOLD.OTF
#        - asset: assets/fonts/SFProText-Regular.ttf
